version: '2'
volumes:
    maven-repo:
        driver: local        
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "someDummyPassw0rd"
      MYSQL_DATABASE: cb_sap_importer
    ports:
      - "33000:3306"
  app:
    image: demo:latest
    volumes:
      - maven-repo:/root/.m2
    links:
      - db
    depends_on:
      - db
